
const GAUGE_BORDER_THICKNESS = 0.08
const GAUGE_BORDER_GAP       = 0.06

const GAUGE_TEXT_SIZE        = 0.9
const GAUGE_TEXT_POSITION    = 0.5

const GAUGE_FILLING_DURATION = 2500

export const constants = {
  GAUGE_BORDER_THICKNESS,
  GAUGE_BORDER_GAP,
  GAUGE_TEXT_SIZE,
  GAUGE_TEXT_POSITION,
  GAUGE_FILLING_DURATION
}
