imports:
    - { resource: framework_dev.yml }

framework:
    test: true
    session:
        handler_id: null
        storage_factory_id: session.storage.factory.mock_file
    profiler:
        enabled: false
