services:
    _defaults:
        public: true # required by controllers

    Claroline\PrivacyBundle\Controller\PrivacyController:
        parent: Claroline\AppBundle\Controller\AbstractSecurityController
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\PrivacyBundle\Manager\PrivacyManager'
            - '@Claroline\PrivacyBundle\Manager\MailManager'
