services:
  Claroline\YouTubeBundle\Component\Resource\VideoResource:
    tags: ['claroline.component.resource', 'kernel.event_subscriber']
    arguments:
      - '@Claroline\YouTubeBundle\Manager\YouTubeManager'
