const TRACKING_EVENT_GENERIC    = 'generic'
const TRACKING_EVENT_EVALUATION = 'evaluation'
const TRACKING_EVENT_COMMUNITY  = 'community'
const TRACKING_EVENT_CONTENT    = 'content'
const TRACKING_EVENT_BADGE      = 'badge'

const TRACKING_EVENTS = {
  [TRACKING_EVENT_GENERIC]: {
    icon: 'fa fa-flash'
  },
  [TRACKING_EVENT_EVALUATION]: {
    icon: 'fa fa-check-square-o'
  },
  [TRACKING_EVENT_COMMUNITY]: {
    icon: 'fa fa-users'
  },
  [TRACKING_EVENT_CONTENT]: {
    icon: 'fa fa-eye'
  },
  [TRACKING_EVENT_BADGE]: {
    icon: 'fa fa-trophy'
  }
}

const STATUS_PASSED = 'passed'
const STATUS_FAILED = 'failed'
const STATUS_COMPLETED = 'completed'
const STATUS_INCOMPLETE = 'incomplete'
const STATUS_NOT_ATTEMPTED = 'not_attempted'
const STATUS_UNKNOWN = 'unknown'
const STATUS_OPENED = 'opened'
const STATUS_PARTICIPATED = 'participated'

const TRACKING_STATUS = [
  STATUS_PASSED,
  STATUS_FAILED,
  STATUS_COMPLETED,
  STATUS_INCOMPLETE,
  STATUS_NOT_ATTEMPTED,
  STATUS_UNKNOWN,
  STATUS_OPENED,
  STATUS_PARTICIPATED
]

export const constants = {
  TRACKING_EVENTS,
  TRACKING_EVENT_GENERIC,
  TRACKING_EVENT_EVALUATION,
  TRACKING_EVENT_COMMUNITY,
  TRACKING_EVENT_CONTENT,
  TRACKING_EVENT_BADGE,
  STATUS_PASSED,
  STATUS_FAILED,
  STATUS_COMPLETED,
  STATUS_INCOMPLETE,
  STATUS_NOT_ATTEMPTED,
  STATUS_UNKNOWN,
  STATUS_OPENED,
  STATUS_PARTICIPATED,
  TRACKING_STATUS
}
