services:
    Claroline\AuthenticationBundle\Manager\MailManager:
        arguments:
            - '@router'
            - '@event_dispatcher'
            - '@Claroline\CoreBundle\Manager\MailManager'
            - '@Claroline\CoreBundle\Manager\LocaleManager'
            - '@Claroline\CoreBundle\Manager\Template\TemplateManager'
            - '@Claroline\CoreBundle\Manager\UserManager'

    Claroline\AuthenticationBundle\Manager\AuthenticationManager:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\AuthenticationBundle\Manager\OAuthManager:
        arguments:
            - '@router'
            - '@Claroline\AuthenticationBundle\Component\OAuth\OAuth2Provider'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
