services:
    _defaults:
        tags: [security.voter]

    Claroline\AuthenticationBundle\Security\Voter\ApiTokenVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter

    Claroline\AuthenticationBundle\Security\Voter\IpUserVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter

    Claroline\AuthenticationBundle\Security\Voter\OAuthClientVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter
