services:
    Claroline\CommunityBundle\Messenger\AddEveryoneToGroupHandler:
        tags: [ messenger.message_handler ]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'

    Claroline\CommunityBundle\Messenger\DisableInactiveUsersHandler:
        tags: [ messenger.message_handler ]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\UserManager'

    Claroline\CommunityBundle\Messenger\GenerateUserRolesHandler:
        tags: [ messenger.message_handler ]
        arguments:
            - '@security.token_storage'
            - '@messenger.default_bus'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\RoleManager'

    Claroline\CommunityBundle\Messenger\ReassignGroupOrganizationHandler:
        tags: [ messenger.message_handler ]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CommunityBundle\Messenger\ReassignUserOrganizationHandler:
        tags: [ messenger.message_handler ]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
