services:
    _defaults:
        public: true

    Claroline\EvaluationBundle\Controller\Certificate\SequenceCertificateController:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\EvaluationBundle\Manager\SequenceCertificateManager'

    Claroline\EvaluationBundle\Controller\Certificate\WorkspaceCertificateController:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\EvaluationBundle\Manager\WorkspaceCertificateManager'

    Claroline\EvaluationBundle\Controller\SkillsFrameworkController:
        parent: Claroline\AppBundle\Controller\AbstractCrudController
        public: true

    Claroline\EvaluationBundle\Controller\Workspace\ActivityController:
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
            - '@Claroline\AppBundle\Manager\ViewerManager'

    # Sequences
    Claroline\EvaluationBundle\Controller\Sequence\ActivityController:
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Manager\ViewerManager'

    Claroline\EvaluationBundle\Controller\Sequence\SequenceController:
        parent: Claroline\AppBundle\Controller\AbstractCrudController
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
            - '@Claroline\EvaluationBundle\Manager\SequenceManager'
            - '@Claroline\EvaluationBundle\Manager\SequenceRestrictionsManager'
            - '@Claroline\EvaluationBundle\Manager\SequenceEvaluationManager'

    # User evaluations
    Claroline\EvaluationBundle\Controller\UserEvaluation\WorkspaceEvaluationController:
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\EvaluationBundle\Manager\WorkspaceEvaluationManager'
            - '@Claroline\EvaluationBundle\Manager\ExportManager'

    Claroline\EvaluationBundle\Controller\UserEvaluation\SequenceEvaluationController:
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
            - '@Claroline\EvaluationBundle\Manager\SequenceEvaluationManager'
            - '@Claroline\EvaluationBundle\Manager\ExportManager'

    Claroline\EvaluationBundle\Controller\UserEvaluation\ResourceEvaluationController:
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
            - '@Claroline\EvaluationBundle\Manager\ResourceEvaluationManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\EvaluationBundle\Manager\ExportManager'

    Claroline\EvaluationBundle\Controller\UserEvaluation\ResourceAttemptController:
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\API\Crud'
