services:
    Claroline\EvaluationBundle\Finder\EvaluationType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\ResourceAttemptType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\ResourceEvaluationType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\WorkspaceEvaluationType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\SequenceType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\SequenceViewType:
        tags: [ claroline.finder.type ]

    Claroline\EvaluationBundle\Finder\SequenceEvaluationType:
        tags: [ claroline.finder.type ]

    # deprecated
    Claroline\EvaluationBundle\Finder\WorkspaceEvaluationFinder:
        parent: Claroline\AppBundle\API\Finder\AbstractFinder
        tags: [ claroline.finder ]

    Claroline\EvaluationBundle\Finder\ResourceEvaluationFinder:
        parent: Claroline\AppBundle\API\Finder\AbstractFinder
        tags: [ claroline.finder ]

    Claroline\EvaluationBundle\Finder\ResourceUserEvaluationFinder:
        parent: Claroline\AppBundle\API\Finder\AbstractFinder
        tags: [ claroline.finder ]
