services:
    _defaults:
        tags: [ claroline.serializer ]

    Claroline\EvaluationBundle\Serializer\UserEvaluation\WorkspaceEvaluationSerializer:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'

    Claroline\EvaluationBundle\Serializer\UserEvaluation\ResourceEvaluationSerializer:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'

    Claroline\EvaluationBundle\Serializer\UserEvaluation\ResourceAttemptSerializer:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'

    Claroline\EvaluationBundle\Serializer\UserEvaluation\SequenceEvaluationSerializer:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\EvaluationBundle\Serializer\Sequence\SequenceSerializer'
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'

    Claroline\EvaluationBundle\Serializer\CertificateSerializer:
        arguments:
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'
            - '@Claroline\EvaluationBundle\Serializer\UserEvaluation\WorkspaceEvaluationSerializer'

    Claroline\EvaluationBundle\Serializer\SkillsFrameworkSerializer: ~

    # Sequences
    Claroline\EvaluationBundle\Serializer\Sequence\SequenceSerializer:
        arguments:
            - '@event_dispatcher'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\TemplateBundle\Serializer\TemplateSerializer'
            - '@Claroline\CommunityBundle\Serializer\UserSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
            - '@Claroline\EvaluationBundle\Serializer\Sequence\StepSerializer'
            - '@Claroline\EvaluationBundle\Serializer\Sequence\AssignmentSerializer'

    Claroline\EvaluationBundle\Serializer\Sequence\StepSerializer:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'

    Claroline\EvaluationBundle\Serializer\Sequence\RequirementSerializer:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\EvaluationBundle\Serializer\Sequence\SequenceSerializer'

    Claroline\EvaluationBundle\Serializer\Sequence\AssignmentSerializer:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CommunityBundle\Serializer\RoleSerializer'
