services:
    Claroline\EvaluationBundle\Subscriber\GlobalSearchSubscriber:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
        tags:
            - { name: kernel.event_subscriber }

    Claroline\EvaluationBundle\Subscriber\ResourceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Subscriber\SequenceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@Claroline\EvaluationBundle\Manager\SequenceEvaluationManager'

    Claroline\EvaluationBundle\Subscriber\WorkspaceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@messenger.default_bus'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\EvaluationBundle\Manager\WorkspaceEvaluationManager'

    Claroline\EvaluationBundle\Subscriber\Crud\SequenceSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\CoreBundle\Manager\FileManager'

    Claroline\EvaluationBundle\Subscriber\Certificate\WorkspaceCertificateSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@Claroline\EvaluationBundle\Manager\WorkspaceCertificateManager'

    Claroline\EvaluationBundle\Subscriber\Certificate\SequenceCertificateSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@Claroline\EvaluationBundle\Manager\SequenceCertificateManager'
