services:
    _defaults:
        tags: [security.voter]

    Claroline\EvaluationBundle\Security\Voter\SequenceVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Security\Voter\WorkspaceEvaluationVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter

    Claroline\EvaluationBundle\Security\Voter\SequenceEvaluationVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter

    Claroline\EvaluationBundle\Security\Voter\ResourceEvaluationVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter

    Claroline\EvaluationBundle\Security\Voter\ResourceAttemptVoter:
        parent: Claroline\AppBundle\Security\Voter\AbstractVoter