#!/usr/bin/php
<?php

/**
 * This pre-commit hook checks for ESLint errors.
 */
$moduleBinDir = __DIR__.'/../../../../../../../node_modules/.bin';
$eslint = realpath("{$moduleBinDir}/eslint");

if (!$eslint) {
    echo "Cannot found eslint (looked in {$moduleBinDir}) \n";
    exit(1);
}

// collect all files which have been added, copied or
// modified and store them in an array called output
exec('git diff --cached --name-status --diff-filter=ACM', $output);

// filter js(x) files
$files = array_filter($output, function ($line) {
    $file = trim(substr($line, 1));

    return preg_match('#Resources/modules/.+\.jsx?$#', $file);
});

$fileString = implode($files, ' ');

// exec eslint
exec("{$eslint} {$fileString}", $output, $code);

if ($code !== 0) {
    echo implode("\n", $output)."\n";
    exit(1);
}
