#!/usr/bin/php
<?php

/**
 * This pre-commit hook checks for PHPMD errors.
 */

$binDir = __DIR__.'/../../../../../../bin';
$phpmd = realpath("{$binDir}/phpmd");

if (!$phpmd) {
    echo "Cannot found php-cs-fixer (looked in {$binDir}) \n";
    exit(1);
}

// collect all files which have been added, copied or
// modified and store them in an array called output
exec('git diff --cached --name-status --diff-filter=ACM', $files);

foreach ($files as $file) {
    $fileName = trim(substr($file, 1));

    if (pathinfo($fileName, PATHINFO_EXTENSION) === 'php') {
        exec("{$phpmd} {$fileName} text phpmd.xml", $output, $code);

        if ($code !== 0) {
            echo implode("\n", $output)."\n";
            exit(1);
        }
    }
}
