#!/usr/bin/php
<?php

/**
 * This pre-commit hook checks for ESLint errors.
 */

$moduleBinDir = __DIR__.'/../../../../../../../node_modules/.bin';
$eslint = realpath("{$moduleBinDir}/eslint");

if (!$eslint) {
    echo "Cannot found eslint (looked in {$moduleBinDir}) \n";
    exit(1);
}

// collect all files which have been added, copied or
// modified and store them in an array called output
exec('git diff --cached --name-status --diff-filter=ACM', $files);

foreach ($files as $file) {
    $fileName = trim(substr($file, 1));

    if (preg_match('#Resources/modules/.+\.js$#', $fileName)) {
        exec("{$eslint} {$fileName}", $output, $code);

        if ($code !== 0) {
            echo implode("\n", $output)."\n";
            exit(1);
        }
    }
}
