
const CALENDAR_VIEW_DAYS   = 'days'
const CALENDAR_VIEW_MONTHS = 'months'
const CALENDAR_VIEW_YEARS  = 'years'

const CALENDAR_VIEWS = [
  CALENDAR_VIEW_DAYS,
  CALENDAR_VIEW_MONTHS,
  CALENDAR_VIEW_YEARS
]

export const constants = {
  CALENDAR_VIEWS,
  CALENDAR_VIEW_DAYS,
  CALENDAR_VIEW_MONTHS,
  CALENDAR_VIEW_YEARS
}
