import {makeActionCreator} from '#/main/app/store/actions'
import {API_REQUEST} from '#/main/app/api'

export const CURRENT_TAB              = 'CURRENT_TAB'
export const TABS_LOAD                = 'TABS_LOAD'
export const TAB_LOAD                 = 'TAB_LOAD'
export const TAB_SET_LOADED           = 'TAB_SET_LOADED'
export const TAB_SET_ERROR = 'TAB_SET_ERROR'
export const TAB_UPDATE_VIEWS = 'TAB_UPDATE_VIEWS'

export const actions = {}

actions.setCurrentTab = makeActionCreator(CURRENT_TAB, 'tab')
actions.setTabLoaded = makeActionCreator(TAB_SET_LOADED, 'loaded')
actions.loadTab = makeActionCreator(TAB_LOAD, 'homeTab', 'managed', 'accessErrors')
actions.updateViews = makeActionCreator(TAB_UPDATE_VIEWS, 'tabId', 'nbViews')
actions.setError = makeActionCreator(TAB_SET_ERROR, 'code', 'message', 'additional')

actions.fetchTab = (tab) => (dispatch) => {
  // if the tab has no id, it's the default one generated by ui if there is no tab
  // it does not exist, so we don't call the server
  if (tab.id) {
    return dispatch({
      [API_REQUEST]: {
        silent: true,
        url: ['apiv2_home_tab_open', {id: tab.id}],
        before: () => dispatch(actions.setTabLoaded(false)),
        success: (response) => dispatch(actions.loadTab(response.homeTab, null)),
        error: (response, status) => {
          switch (status) {
            case 404:
              dispatch(actions.setError('NOT_FOUND', 'Home tab not found.', null))
              break
            case 500:
              dispatch(actions.setError('UNKNOWN_ERROR', response.message, response.trace))
              break
            case 401:
            case 403:
              // the response contains why we can't access the resource and the minimal representation of the resource node
              dispatch(actions.loadTab(response.homeTab, response.error))
              break
          }
        }
      }
    })
  }

  return dispatch(actions.loadTab(tab, false, []))
}

actions.checkAccessCode = (tab, code) => (dispatch) => dispatch({
  [API_REQUEST] : {
    url: ['apiv2_home_tab_unlock', {id: tab.id}],
    request: {
      method: 'POST',
      body: JSON.stringify({code: code})
    },
    success: () => dispatch(actions.setTabLoaded(false)) // force reload the tab
  }
})

actions.updateView = (tab) => (dispatch) => dispatch({
  [API_REQUEST] : {
    silent: true,
    url: ['apiv2_home_tab_view_update', {id: tab.id}],
    request: {
      method: 'PUT'
    },
    success: (response) => dispatch(actions.updateViews(tab.id, response.nbViews))
  }
})

