#!/usr/bin/php
<?php

/**
 * This pre-commit hook checks for PHP-CS-fixer errors.
 *
 * @authors Mardix  http://github.com/mardix, Donovan Tengblad http://github.com/purplefish32
 *
 * @since   Sept 4 2012
 */
$binDir = __DIR__.'/../../../../../../bin';
$csFixer = realpath("{$binDir}/php-cs-fixer");
$configFile = __DIR__.'/../config/phpcs.php';

if (!$csFixer) {
    echo "Cannot found php-cs-fixer (looked in {$binDir}) \n";
    exit(1);
}

// collect all files which have been added, copied or
// modified and store them in an array called output
exec('git diff --cached --name-status --diff-filter=ACM', $files);

foreach ($files as $file) {
    $fileName = trim(substr($file, 1));

    if (pathinfo($fileName, PATHINFO_EXTENSION) === 'php') {
        // check there's no syntax errors
        exec('php -l '.escapeshellarg($fileName), $output, $return);

        if ($return === 0) {
            // fix file and add it back
            exec("{$csFixer} fix {$fileName} --config={$configFile}; git add {$fileName}");
        } else {
            echo implode("\n", $output)."\n";
            exit(1);
        }
    }
}
