services:
    Claroline\PrivacyBundle\Component\Template\PrivacyTemplate:
        parent: Claroline\TemplateBundle\Component\Template\TemplateComponent
        tags: [ 'claroline.component.template' ]

    Claroline\PrivacyBundle\Component\Template\TermsOfServiceTemplate:
        parent: Claroline\TemplateBundle\Component\Template\TemplateComponent
        tags: [ 'claroline.component.template' ]

    Claroline\PrivacyBundle\Component\Template\RequestAccountDeletionEmail:
        parent: Claroline\TemplateBundle\Component\Template\TemplateComponent
        tags: [ 'claroline.component.template' ]
