<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Category by user
     *
     * @access public
     *
     * @param integer id User
     *
     * Return queryBuilder
     */
    public function getUserCategory($uid)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('c.user', 'u')
            ->where($qb->expr()->in('u.id', $uid))
            ->orderBy('c.value', 'ASC');

        //request used by a form, queryBuilder must be given and not an array
        return $qb;
    }
}