<?php

namespace Innova\PathBundle\Repository;

/**
 * CriterionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterionRepository extends \Doctrine\ORM\EntityRepository
{
}
