<?php

/**
 * ExoOnLine
 * Copyright or © or Copr. Université Jean Monnet (France), 2012
 * dsi.dev@univ-st-etienne.fr
 *
 * This software is a computer program whose purpose is to [describe
 * functionalities and technical features of your software].
 *
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
*/

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findByType($type, $userID, $searchLabel)
    {
        if ($type == 'image') {
            $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d WHERE d.user = '.$userID.' AND
                (d.type= \'.png\' OR d.type= \'.jpeg\' OR d.type= \'.jpg\' OR d.type= \'.gif\' OR d.type= \'.bmp\')';
        } elseif ($type == 'video') {
            $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d WHERE d.user = '.$userID.' AND
                (d.type= \'.avi\' OR d.type= \'.mpeg\' OR d.type= \'.wmv\' OR d.type= \'.flv\' OR d.type= \'.mov\')';
        } elseif ($type == 'music') {
            $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d WHERE d.user = '.$userID.' AND
                (d.type= \'.mp3\' OR d.type= \'.wav\')';
        } elseif ($type == 'file') {
            $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d WHERE d.user = '.$userID.' AND NOT
                d.type= \'.png\' AND NOT d.type= \'.jpeg\' AND NOT d.type= \'.jpg\' AND NOT d.type= \'.gif\' AND NOT d.type= \'.bmp\'
                AND NOT d.type= \'.avi\' AND NOT d.type= \'.mpeg\' AND NOT d.type= \'.wmv\' AND NOT d.type= \'.flv\' AND NOT d.type= \'.mov\'';
        } elseif ($type == 'all') {
            $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d WHERE d.user = '.$userID.'';
        }

        if ($searchLabel != '') {
            $dql .= ' AND UPPER(d.label) LIKE :search';
            $query = $this->_em->createQuery($dql)->setParameter('search', "%{$searchLabel}%");
        } else {
            $query = $this->_em->createQuery($dql);
        }

        return $query->getResult();
    }

    public function findByLabel($labelToFind, $userId)
    {
        $dql = 'SELECT d FROM UJM\ExoBundle\Entity\Document d
            WHERE d.user = '.$userId.'
            AND UPPER(d.label) LIKE :search';

        $query = $this->_em->createQuery($dql)
            ->setParameter('search', "%{$labelToFind}%");

        return $query->getResult();
    }
}