<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionGraphicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionGraphicRepository extends EntityRepository
{
    /**
     * Get InteractionGraphic linked with an interaction
     *
     * @access public
     *
     * @param integer $interactionId id Interaction
     *
     * Return array[InteractionGraphic]
     */
    public function getInteractionGraphic($interactionId)
    {
        $qb = $this->createQueryBuilder('igraph');

        $qb->join('igraph.interaction', 'i')
           ->where($qb->expr()->in('i.id', $interactionId));

        return $qb->getQuery()->getSingleResult();
    }
}
