<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionMatchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionMatchingRepository extends EntityRepository
{
    
    /**
     * Get InteractionMatching linked with an interaction
     *
     * @access public
     *
     * @param integer $interactionId id Interaction
     *
     * Return array[InteractionMatching]
     */
    public function getInteractionMatching($interactionId)
    {
        $qb = $this->createQueryBuilder('im');
        $qb->join('im.interaction', 'i')
            ->where($qb->expr()->in('i.id', $interactionId));

        return $qb->getQuery()->getSingleResult();
    }

}
