<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionHoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionHoleRepository extends EntityRepository
{
    /**
     * Get InteractionHole linked with an interaction
     *
     * @access public
     *
     * @param integer $interactionId id Interaction
     *
     * Return array[InteractionHole]
     */
    public function getInteractionHole($interactionId)
    {
        $qb = $this->createQueryBuilder('ihole');
        $qb->join('ihole.interaction', 'i')
            ->where($qb->expr()->in('i.id', $interactionId));

        return $qb->getQuery()->getSingleResult();
    }

}
