<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
    /**
     * Allow to know if exists already a response for a question of a student's paper
     *
     */
    public function getAlreadyResponded($paperID, $interactionID)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->join('r.paper', 'p')
            ->join('r.interaction', 'i')
            ->where($qb->expr()->in('p.id', $paperID))
            ->andWhere($qb->expr()->in('i.id', $interactionID));

        return $qb->getQuery()->getResult();
    }

    /**
     * Send the reponses for a paper
     *
     */
    public function getPaperResponses($uid, $paperID)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->join('r.paper', 'p')
            ->join('p.user', 'u')
            ->where($qb->expr()->in('p.id', $paperID))
            ->andWhere($qb->expr()->in('u.id', $uid));

        return $qb->getQuery()->getResult();
    }

    /**
     * Send the reponses for an exercise and an interaction with count
     *
     */
    public function getExerciseInterResponsesWithCount($exoId, $interId)
    {
        $dql = 'SELECT r.mark, count(r.mark) as nb
            FROM UJM\ExoBundle\Entity\Response r, UJM\ExoBundle\Entity\Interaction i, UJM\ExoBundle\Entity\Question q, UJM\ExoBundle\Entity\Paper p
            WHERE r.interaction=i.id AND i.question=q.id AND r.paper=p.id AND p.exercise='.$exoId.' AND r.interaction ='.$interId.' AND r.response != \'\' GROUP BY r.mark';

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }

    /**
     * Send the reponses for an exercise and an interaction
     *
     */
    public function getExerciseInterResponses($exoId, $interId)
    {
        $dql = 'SELECT r.mark
            FROM UJM\ExoBundle\Entity\Response r, UJM\ExoBundle\Entity\Interaction i, UJM\ExoBundle\Entity\Question q, UJM\ExoBundle\Entity\Paper p
            WHERE r.interaction=i.id AND i.question=q.id AND r.paper=p.id AND p.exercise='.$exoId.' AND r.interaction ='.$interId.' ORDER BY p.id';

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }
}