<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \UJM\ExoBundle\Entity\Exercise;

/**
 * StepRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class StepRepository extends EntityRepository {
    
    /**
     * Returns the step default. (En attendant d'avoir la partie gestion des steps)
     *
     * @param Exercice $exo
     * @return Question[]
     */
    public function findByExercise(Exercise $exo){ 

        return $this->createQueryBuilder('s')
            ->join('s.exercise','e')
            ->where('e = :exercise')
            ->setParameter(':exercise', $exo)
            ->getQuery()
            ->getResult();
    }
}
