<?php

namespace Innova\PathBundle\Repository;

/**
 * StepConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
