<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    /**
     * Allow to know if the User is recorded in Subscription
     * old entity, will be delete in the futur.
     *
     *
     * @param int $user     id User
     * @param int $exercise id Exercise
     *
     * Return array[Subscription]
     */
    public function getControlExerciseEnroll($user, $exercise)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->join('s.exercise', 'e')
            ->join('s.user', 'u')
            ->where($qb->expr()->in('e.id', $exercise))
            ->andWhere($qb->expr()->in('u.id', $user));

        return $qb->getQuery()->getResult();
    }
}
