import {trans} from '#/main/app/intl/translation'

const TIMEZONE_CODES = [
  'Pacific/Midway',
  'US/Samoa',
  'US/Hawaii',
  'US/Alaska',
  'US/Pacific',
  'America/Tijuana',
  'US/Arizona',
  'US/Mountain',
  'America/Chihuahua',
  'America/Mazatlan',
  'America/Mexico_City',
  'America/Monterrey',
  'Canada/Saskatchewan',
  'US/Central',
  'US/Eastern',
  'US/East-Indiana',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'Canada/Atlantic',
  'America/La_Paz',
  'America/Santiago',
  'Canada/Newfoundland',
  'America/Buenos_Aires',
  'Greenland',
  'Atlantic/Stanley',
  'Atlantic/Azores',
  'Atlantic/Cape_Verde',
  'Africa/Casablanca',
  'Europe/Dublin',
  'Europe/Lisbon',
  'Europe/London',
  'Africa/Monrovia',
  'Europe/Amsterdam',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Bratislava',
  'Europe/Brussels',
  'Europe/Budapest',
  'Europe/Copenhagen',
  'Europe/Ljubljana',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Prague',
  'Europe/Rome',
  'Europe/Sarajevo',
  'Europe/Skopje',
  'Europe/Stockholm',
  'Europe/Vienna',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Europe/Athens',
  'Europe/Bucharest',
  'Africa/Cairo',
  'Africa/Harare',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Asia/Jerusalem',
  'Europe/Kiev',
  'Europe/Minsk',
  'Europe/Riga',
  'Europe/Sofia',
  'Europe/Tallinn',
  'Europe/Vilnius',
  'Asia/Baghdad',
  'Asia/Kuwait',
  'Africa/Nairobi',
  'Asia/Riyadh',
  'Europe/Moscow',
  'Asia/Tehran',
  'Asia/Baku',
  'Europe/Volgograd',
  'Asia/Muscat',
  'Asia/Tbilisi',
  'Asia/Yerevan',
  'Asia/Kabul',
  'Asia/Karachi',
  'Asia/Tashkent',
  'Asia/Kolkata',
  'Asia/Kathmandu',
  'Asia/Yekaterinburg',
  'Asia/Almaty',
  'Asia/Dhaka',
  'Asia/Novosibirsk',
  'Asia/Bangkok',
  'Asia/Jakarta',
  'Asia/Krasnoyarsk',
  'Asia/Chongqing',
  'Asia/Hong_Kong',
  'Asia/Kuala_Lumpur',
  'Australia/Perth',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Ulaanbaatar',
  'Asia/Urumqi',
  'Asia/Irkutsk',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Asia/Yakutsk',
  'Australia/Brisbane',
  'Australia/Canberra',
  'Pacific/Guam',
  'Australia/Hobart',
  'Australia/Melbourne',
  'Pacific/Port_Moresby',
  'Australia/Sydney',
  'Asia/Vladivostok',
  'Asia/Magadan',
  'Pacific/Auckland',
  'Pacific/Fiji'
]

/**
 * The list of world timezones with translated names.
 * Can be used in a <Select />
 *
 * @type {object}
 */
const TIMEZONES = TIMEZONE_CODES
  .reduce((timezones, timezoneCode) => Object.assign(timezones,{
    [timezoneCode]: trans(timezoneCode, {}, 'timezones')
  }), {})

export const constants = {
  TIMEZONE_CODES,
  TIMEZONES
}
