<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\CoreBundle\Event\Resource;

use Claroline\CoreBundle\Entity\Resource\AbstractResource;
use Symfony\Component\HttpFoundation\Response;

/**
 * An event which is dispatched when an action is requested on a Resource.
 */
class ResourceActionEvent extends ResourceEvent
{
    /**
     * The data passed to the action (eg. new data).
     *
     * NB. Data depend on the requested action, so we can not validate it.
     * This is the duty of the attached listener to check it gets what it wants.
     *
     * @var array
     */
    private $data = null;

    /**
     * The options of the action (eg. list query string).
     *
     * NB. Options depend on the requested action, so we can not validate them.
     * This is the duty of the attached listener to check it gets what it wants.
     *
     * @var array
     */
    private $options = [];

    /**
     * The response generated by the action.
     *
     * @var Response
     */
    private $response = null;

    /**
     * ResourceActionEvent constructor.
     *
     * @param AbstractResource $resource
     * @param array            $options
     * @param array            $data
     */
    public function __construct(
        AbstractResource $resource,
        array $options = [],
        array $data = null)
    {
        parent::__construct($resource);

        $this->data = $data;
        $this->options = $options;
    }

    /**
     * @return array
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * @return array
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * @return Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * @param Response $response
     */
    public function setResponse(Response $response)
    {
        $this->response = $response;
    }
}
