services:
    Claroline\PeerTubeBundle\Component\Resource\VideoResource:
        tags: ['claroline.component.resource', 'kernel.event_subscriber']
        arguments:
            - '@twig'
            - '@Claroline\PeerTubeBundle\Manager\PeerTubeManager'
