services:
    Claroline\EvaluationBundle\Component\Tool\ProgressionTool:
        parent: Claroline\AppBundle\Component\Tool\ToolComponent
        tags: [ 'claroline.component.tool' ]
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\EvaluationBundle\Manager\WorkspaceEvaluationManager'
