plugin:
    resources:
        - name: file
          class: Claroline\CoreBundle\Entity\Resource\File

        - name: directory
          class: Claroline\CoreBundle\Entity\Resource\Directory

    tools:
        - name: workspaces
          icon: book
          tool_rights:
              - archive
              - create

        - name: resources
          icon: folder

        - name: locations
          icon: map-marker-alt

        - name: parameters
          icon: cog

        - name: integration
          icon: plug

    widgets:
        - name: simple
          class: Claroline\CoreBundle\Entity\Widget\Type\SimpleWidget
          context: [workspace, desktop, public, administration]
          tags: [content]

        - name: list
          class: Claroline\CoreBundle\Entity\Widget\Type\ListWidget
          context: [workspace, desktop, public, administration]
          sources: [list]

        - name: resource
          class: Claroline\CoreBundle\Entity\Widget\Type\ResourceWidget
          context: [workspace, desktop, public, administration]
