services:
    Claroline\AuthenticationBundle\Component\Tool\AuthenticationTool:
        parent: Claroline\AppBundle\Component\Tool\ToolComponent
        tags: [ 'claroline.component.tool' ]
        arguments:
            - '@router'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AuthenticationBundle\Manager\AuthenticationManager'
            - '@Claroline\AuthenticationBundle\Manager\OAuthManager'
