<?php

namespace Claroline\CoreBundle\Migrations\ibm_db2;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated migration based on mapping information: modify it with caution
 *
 * Generation date: 2013/09/03 05:00:43
 */
class Version20130903170043 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            CREATE TABLE claro_resource_mask_decoder (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                resource_type_id INTEGER NOT NULL, 
                \"value\" INTEGER NOT NULL, 
                name VARCHAR(255) NOT NULL, 
                PRIMARY KEY(id)
            )
        ");
        $this->addSql("
            CREATE INDEX IDX_39D93F4298EC6B7B ON claro_resource_mask_decoder (resource_type_id)
        ");
        $this->addSql("
            CREATE TABLE claro_menu_action (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                resource_type_id INTEGER DEFAULT NULL, 
                name VARCHAR(255) DEFAULT NULL, 
                async SMALLINT DEFAULT NULL, 
                is_custom SMALLINT NOT NULL, 
                is_form SMALLINT NOT NULL, 
                \"value\" VARCHAR(255) DEFAULT NULL, 
                PRIMARY KEY(id)
            )
        ");
        $this->addSql("
            CREATE INDEX IDX_1F57E52B98EC6B7B ON claro_menu_action (resource_type_id)
        ");
        $this->addSql("
            ALTER TABLE claro_resource_mask_decoder 
            ADD CONSTRAINT FK_39D93F4298EC6B7B FOREIGN KEY (resource_type_id) 
            REFERENCES claro_resource_type (id) 
            ON DELETE CASCADE
        ");
        $this->addSql("
            ALTER TABLE claro_menu_action 
            ADD CONSTRAINT FK_1F57E52B98EC6B7B FOREIGN KEY (resource_type_id) 
            REFERENCES claro_resource_type (id) 
            ON DELETE SET NULL
        ");
        $this->addSql("
            ALTER TABLE claro_resource_rights 
            ADD COLUMN mask INTEGER NOT NULL 
            DROP COLUMN can_delete 
            DROP COLUMN can_open 
            DROP COLUMN can_edit 
            DROP COLUMN can_copy 
            DROP COLUMN can_export
        ");
    }

    public function down(Schema $schema)
    {
        $this->addSql("
            DROP TABLE claro_resource_mask_decoder
        ");
        $this->addSql("
            DROP TABLE claro_menu_action
        ");
        $this->addSql("
            ALTER TABLE claro_resource_rights 
            ADD COLUMN can_delete SMALLINT NOT NULL 
            ADD COLUMN can_open SMALLINT NOT NULL 
            ADD COLUMN can_edit SMALLINT NOT NULL 
            ADD COLUMN can_copy SMALLINT NOT NULL 
            ADD COLUMN can_export SMALLINT NOT NULL 
            DROP COLUMN mask
        ");
    }
}