const ISSUING_MODE_ORGANIZATION = 'organization'
const ISSUING_MODE_USER = 'user'
const ISSUING_MODE_GROUP = 'group'
const ISSUING_MODE_PEER = 'peer'
const ISSUING_MODE_WORKSPACE = 'workspace'

export {
  ISSUING_MODE_ORGANIZATION,
  ISSUING_MODE_USER,
  ISSUING_MODE_GROUP,
  ISSUING_MODE_PEER,
  ISSUING_MODE_WORKSPACE
}
