<?php

namespace Claroline\ForumBundle\Migrations\pdo_ibm;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated migration based on mapping information: modify it with caution
 *
 * Generation date: 2013/09/04 05:02:30
 */
class Version20130904170227 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            ALTER TABLE claro_forum ALTER id id INTEGER NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum_message ALTER id id INTEGER NOT NULL ALTER content content CLOB(1M) NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum_options ALTER id id INTEGER NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum_subject ALTER id id INTEGER NOT NULL
        ");
    }

    public function down(Schema $schema)
    {
        $this->addSql("
            ALTER TABLE claro_forum_options ALTER id id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum_message ALTER id id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL ALTER content content VARCHAR(255) NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum_subject ALTER id id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        ");
        $this->addSql("
            ALTER TABLE claro_forum ALTER id id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        ");
    }
}