<?php

namespace Claroline\ScormBundle\Migrations\pdo_ibm;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated migration based on mapping information: modify it with caution
 *
 * Generation date: 2014/05/05 10:29:14
 */
class Version20140505102910 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            CREATE TABLE claro_scorm_12 (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                hash_name VARCHAR(50) NOT NULL, 
                mastery_score INTEGER DEFAULT NULL, 
                launch_data CLOB(1M) DEFAULT NULL, 
                entry_url VARCHAR(255) NOT NULL, 
                resourceNode_id INTEGER DEFAULT NULL, 
                PRIMARY KEY(id)
            )
        ");
        $this->addSql("
            CREATE UNIQUE INDEX UNIQ_6FE774D5B87FAB32 ON claro_scorm_12 (resourceNode_id)
        ");
        $this->addSql("
            CREATE TABLE claro_scorm_12_info (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                user_id INTEGER NOT NULL, 
                scorm_id INTEGER NOT NULL, 
                score_raw INTEGER DEFAULT NULL, 
                score_min INTEGER DEFAULT NULL, 
                score_max INTEGER DEFAULT NULL, 
                lesson_status VARCHAR(255) DEFAULT NULL, 
                session_time INTEGER DEFAULT NULL, 
                total_time INTEGER DEFAULT NULL, 
                entry VARCHAR(255) DEFAULT NULL, 
                suspend_data CLOB(1M) DEFAULT NULL, 
                credit VARCHAR(255) DEFAULT NULL, 
                exit_mode VARCHAR(255) DEFAULT NULL, 
                lesson_location VARCHAR(255) DEFAULT NULL, 
                lesson_mode VARCHAR(255) DEFAULT NULL, 
                PRIMARY KEY(id)
            )
        ");
        $this->addSql("
            CREATE INDEX IDX_7D2C37E3A76ED395 ON claro_scorm_12_info (user_id)
        ");
        $this->addSql("
            CREATE INDEX IDX_7D2C37E3D75F22BE ON claro_scorm_12_info (scorm_id)
        ");
        $this->addSql("
            ALTER TABLE claro_scorm_12 
            ADD CONSTRAINT FK_6FE774D5B87FAB32 FOREIGN KEY (resourceNode_id) 
            REFERENCES claro_resource_node (id) 
            ON DELETE CASCADE
        ");
        $this->addSql("
            ALTER TABLE claro_scorm_12_info 
            ADD CONSTRAINT FK_7D2C37E3A76ED395 FOREIGN KEY (user_id) 
            REFERENCES claro_user (id) 
            ON DELETE CASCADE
        ");
        $this->addSql("
            ALTER TABLE claro_scorm_12_info 
            ADD CONSTRAINT FK_7D2C37E3D75F22BE FOREIGN KEY (scorm_id) 
            REFERENCES claro_scorm_12 (id) 
            ON DELETE CASCADE
        ");
    }

    public function down(Schema $schema)
    {
        $this->addSql("
            ALTER TABLE claro_scorm_12_info 
            DROP FOREIGN KEY FK_7D2C37E3D75F22BE
        ");
        $this->addSql("
            DROP TABLE claro_scorm_12
        ");
        $this->addSql("
            DROP TABLE claro_scorm_12_info
        ");
    }
}